namespace E_Commerce.Domain.Common.Errors;

public static class ErrorCatalog
{
    public static Error FromCode(string? code)
    {
        return code switch
        {
            ErrorCodes.Common.PageInvalid => CommonErrors.PageInvalid,
            ErrorCodes.Common.PageSizeInvalid => CommonErrors.PageSizeInvalid,

            ErrorCodes.Category.NotFound => CategoryErrors.NotFound,
            ErrorCodes.Category.ParentNotFound => CategoryErrors.ParentNotFound,
            ErrorCodes.Category.ParentSelf => CategoryErrors.ParentSelf,
            ErrorCodes.Category.ParentCycle => CategoryErrors.ParentCycle,
            ErrorCodes.Category.SlugDuplicate => CategoryErrors.SlugAlreadyExists,
            ErrorCodes.Category.DeleteHasChildren => CategoryErrors.DeleteHasChildren,
            ErrorCodes.Category.DeleteHasProducts => CategoryErrors.DeleteHasProducts,
            ErrorCodes.Category.InvalidInput => CategoryErrors.InvalidInput,
            ErrorCodes.Category.IdRequired => CategoryErrors.IdRequired,
            ErrorCodes.Category.ParentInvalid => CategoryErrors.ParentInvalid,
            ErrorCodes.Category.SlugRequired => CategoryErrors.SlugRequired,
            ErrorCodes.Category.SortOrderInvalid => CategoryErrors.SortOrderInvalid,
            ErrorCodes.Category.ChildRequired => CategoryErrors.ChildRequired,
            ErrorCodes.Category.ChildDuplicate => CategoryErrors.ChildDuplicate,

            ErrorCodes.Product.NotFound => ProductErrors.NotFound,
            ErrorCodes.Product.SlugDuplicate => ProductErrors.SlugAlreadyExists,
            ErrorCodes.Product.HasVariants => ProductErrors.HasVariants,
            ErrorCodes.Product.InvalidInput => ProductErrors.InvalidInput,
            ErrorCodes.Product.IdRequired => ProductErrors.IdRequired,
            ErrorCodes.Product.CategoryRequired => ProductErrors.CategoryRequired,
            ErrorCodes.Product.SlugRequired => ProductErrors.SlugRequired,
            ErrorCodes.Product.StatusInvalid => ProductErrors.StatusInvalid,
            ErrorCodes.Product.BasePriceRequired => ProductErrors.BasePriceRequired,
            ErrorCodes.Product.BasePriceInvalid => ProductErrors.BasePriceInvalid,
            ErrorCodes.Product.CurrencyRequired => ProductErrors.CurrencyRequired,
            ErrorCodes.Product.CurrencyInvalid => ProductErrors.CurrencyInvalid,
            ErrorCodes.Product.BrandTooLong => ProductErrors.BrandTooLong,

            ErrorCodes.Variant.NotFound => VariantErrors.NotFound,
            ErrorCodes.Variant.SkuDuplicate => VariantErrors.SkuAlreadyExists,
            ErrorCodes.Variant.DeleteReferenced => VariantErrors.DeleteReferenced,
            ErrorCodes.Variant.InvalidInput => VariantErrors.InvalidInput,
            ErrorCodes.Variant.ProductRequired => VariantErrors.ProductRequired,
            ErrorCodes.Variant.VariantIdRequired => VariantErrors.VariantIdRequired,
            ErrorCodes.Variant.SkuRequired => VariantErrors.SkuRequired,
            ErrorCodes.Variant.SkuTooLong => VariantErrors.SkuTooLong,
            ErrorCodes.Variant.PriceInvalid => VariantErrors.PriceInvalid,
            ErrorCodes.Variant.PriceRequired => VariantErrors.PriceRequired,
            ErrorCodes.Variant.CurrencyRequired => VariantErrors.CurrencyRequired,
            ErrorCodes.Variant.CurrencyInvalid => VariantErrors.CurrencyInvalid,

            ErrorCodes.Auth.InvalidCredentials => AuthErrors.InvalidCredentials,
            ErrorCodes.Auth.InvalidToken => AuthErrors.InvalidToken,
            ErrorCodes.Auth.ExpiredToken => AuthErrors.ExpiredToken,
            ErrorCodes.Auth.TwoFactorRequired => AuthErrors.TwoFactorRequired,
            ErrorCodes.Auth.TwoFactorInvalid => AuthErrors.TwoFactorInvalid,
            ErrorCodes.Auth.TwoFactorSetupRequired => AuthErrors.TwoFactorSetupRequired,
            ErrorCodes.Auth.InvalidRequest => AuthErrors.InvalidRequest,
            ErrorCodes.Auth.PasswordInvalid => AuthErrors.PasswordInvalid,
            ErrorCodes.Auth.PasswordRequired => AuthErrors.PasswordRequired,
            ErrorCodes.Auth.PasswordTooShort => AuthErrors.PasswordTooShort,
            ErrorCodes.Auth.PasswordTooLong => AuthErrors.PasswordTooLong,
            ErrorCodes.Auth.PasswordUppercaseMissing => AuthErrors.PasswordUppercaseMissing,
            ErrorCodes.Auth.PasswordLowercaseMissing => AuthErrors.PasswordLowercaseMissing,
            ErrorCodes.Auth.PasswordDigitMissing => AuthErrors.PasswordDigitMissing,
            ErrorCodes.Auth.PasswordSpecialCharacterMissing => AuthErrors.PasswordSpecialCharacterMissing,
            ErrorCodes.Auth.PasswordWhitespaceInvalid => AuthErrors.PasswordWhitespaceInvalid,
            ErrorCodes.Auth.EmailRequired => AuthErrors.EmailRequired,
            ErrorCodes.Auth.EmailInvalid => AuthErrors.EmailInvalid,
            ErrorCodes.Auth.EmailTooLong => AuthErrors.EmailTooLong,
            ErrorCodes.Auth.TokenRequired => AuthErrors.TokenRequired,

            ErrorCodes.User.NotFound => UserErrors.NotFound,
            ErrorCodes.User.EmailAlreadyExists => UserErrors.EmailAlreadyExists,
            ErrorCodes.User.EmailRequired => UserErrors.EmailRequired,
            ErrorCodes.User.EmailInvalid => UserErrors.EmailInvalid,
            ErrorCodes.User.EmailTooLong => UserErrors.EmailTooLong,
            ErrorCodes.User.FirstNameRequired => UserErrors.FirstNameRequired,
            ErrorCodes.User.FirstNameTooShort => UserErrors.FirstNameTooShort,
            ErrorCodes.User.FirstNameTooLong => UserErrors.FirstNameTooLong,
            ErrorCodes.User.LastNameRequired => UserErrors.LastNameRequired,
            ErrorCodes.User.LastNameTooShort => UserErrors.LastNameTooShort,
            ErrorCodes.User.LastNameTooLong => UserErrors.LastNameTooLong,
            ErrorCodes.User.PhoneRequired => UserErrors.PhoneRequired,
            ErrorCodes.User.PhoneTooLong => UserErrors.PhoneTooLong,
            ErrorCodes.User.PhoneInvalid => UserErrors.PhoneInvalid,
            ErrorCodes.User.NameTooLong => UserErrors.NameTooLong,
            ErrorCodes.User.RoleInvalid => UserErrors.RoleInvalid,

            ErrorCodes.ValueObjects.CurrencyRequired => ValueObjectErrors.CurrencyRequired,
            ErrorCodes.ValueObjects.CurrencyInvalid => ValueObjectErrors.CurrencyInvalid,
            ErrorCodes.ValueObjects.EmailRequired => ValueObjectErrors.EmailRequired,
            ErrorCodes.ValueObjects.EmailInvalid => ValueObjectErrors.EmailInvalid,
            ErrorCodes.ValueObjects.MoneyAmountInvalid => ValueObjectErrors.MoneyAmountInvalid,
            ErrorCodes.ValueObjects.MoneyCurrencyMismatch => ValueObjectErrors.MoneyCurrencyMismatch,
            ErrorCodes.ValueObjects.PasswordHashInvalid => ValueObjectErrors.PasswordHashInvalid,
            ErrorCodes.ValueObjects.TokenHashRequired => ValueObjectErrors.TokenHashRequired,
            ErrorCodes.ValueObjects.TokenHashInvalid => ValueObjectErrors.TokenHashInvalid,
            ErrorCodes.ValueObjects.SlugRequired => ValueObjectErrors.SlugRequired,
            ErrorCodes.ValueObjects.SlugInvalid => ValueObjectErrors.SlugInvalid,
            ErrorCodes.ValueObjects.JsonInvalid => ValueObjectErrors.JsonInvalid,

            ErrorCodes.Domain.TwoFactor.AlreadyDisabled => TwoFactorErrors.AlreadyDisabled,
            ErrorCodes.Domain.TwoFactor.AlreadyEnabled => TwoFactorErrors.AlreadyEnabled,
            ErrorCodes.Domain.TwoFactor.AlreadyVerified => TwoFactorErrors.AlreadyVerified,
            ErrorCodes.Domain.TwoFactor.ChallengeExpired => TwoFactorErrors.ChallengeExpired,
            ErrorCodes.Domain.TwoFactor.ChallengeMaxAttempts => TwoFactorErrors.ChallengeMaxAttempts,
            ErrorCodes.Domain.TwoFactor.NotEnabled => TwoFactorErrors.NotEnabled,
            ErrorCodes.Domain.TwoFactor.NotSetup => TwoFactorErrors.NotSetup,
            ErrorCodes.Domain.TwoFactor.RecoveryInvalid => TwoFactorErrors.RecoveryInvalid,
            ErrorCodes.Domain.TwoFactor.RecoveryUsed => TwoFactorErrors.RecoveryUsed,
            ErrorCodes.Domain.TwoFactor.SecretRequired => TwoFactorErrors.SecretRequired,
            ErrorCodes.Domain.TwoFactor.UserIdRequired => TwoFactorErrors.UserIdRequired,

            ErrorCodes.Domain.AuthToken.ExpiresAtRequired => AuthTokenErrors.ExpiresAtRequired,
            ErrorCodes.Domain.AuthToken.TokenHashRequired => AuthTokenErrors.TokenHashRequired,
            ErrorCodes.Domain.AuthToken.TokenTypeRequired => AuthTokenErrors.TokenTypeRequired,
            ErrorCodes.Domain.AuthToken.UserIdRequired => AuthTokenErrors.UserIdRequired,

            ErrorCodes.Domain.Cart.AnonymousTokenRequired => CartErrors.AnonymousTokenRequired,
            ErrorCodes.Domain.Cart.AnonymousTokenTooLong => CartErrors.AnonymousTokenTooLong,
            ErrorCodes.Domain.Cart.ItemMismatch => CartErrors.ItemMismatch,
            ErrorCodes.Domain.Cart.ItemNotFound => CartErrors.ItemNotFound,
            ErrorCodes.Domain.Cart.ItemRequired => CartErrors.ItemRequired,
            ErrorCodes.Domain.Cart.NotActive => CartErrors.NotActive,
            ErrorCodes.Domain.Cart.NowRequired => CartErrors.NowRequired,
            ErrorCodes.Domain.Cart.StatusInvalid => CartErrors.StatusInvalid,
            ErrorCodes.Domain.Cart.UserIdRequired => CartErrors.UserIdRequired,

            ErrorCodes.Domain.CartItem.CartIdRequired => CartItemErrors.CartIdRequired,
            ErrorCodes.Domain.CartItem.DeltaInvalid => CartItemErrors.DeltaInvalid,
            ErrorCodes.Domain.CartItem.NowRequired => CartItemErrors.NowRequired,
            ErrorCodes.Domain.CartItem.QuantityInvalid => CartItemErrors.QuantityInvalid,
            ErrorCodes.Domain.CartItem.VariantIdRequired => CartItemErrors.VariantIdRequired,

            ErrorCodes.Domain.Category.ChildNotFound => DomainCategoryErrors.ChildNotFound,
            ErrorCodes.Domain.Category.ChildSelf => DomainCategoryErrors.ChildSelf,
            ErrorCodes.Domain.Category.ParentRequired => DomainCategoryErrors.ParentRequired,

            ErrorCodes.Domain.EmailMessage.BodyRequired => EmailMessageErrors.BodyRequired,
            ErrorCodes.Domain.EmailMessage.BodyTooLong => EmailMessageErrors.BodyTooLong,
            ErrorCodes.Domain.EmailMessage.ErrorRequired => EmailMessageErrors.ErrorRequired,
            ErrorCodes.Domain.EmailMessage.ErrorTooLong => EmailMessageErrors.ErrorTooLong,
            ErrorCodes.Domain.EmailMessage.ProviderRequired => EmailMessageErrors.ProviderRequired,
            ErrorCodes.Domain.EmailMessage.ProviderTooLong => EmailMessageErrors.ProviderTooLong,
            ErrorCodes.Domain.EmailMessage.SubjectRequired => EmailMessageErrors.SubjectRequired,
            ErrorCodes.Domain.EmailMessage.SubjectTooLong => EmailMessageErrors.SubjectTooLong,
            ErrorCodes.Domain.EmailMessage.TypeInvalid => EmailMessageErrors.TypeInvalid,

            ErrorCodes.Domain.OAuth.AlreadyLinked => OAuthErrors.AlreadyLinked,
            ErrorCodes.Domain.OAuth.Duplicate => OAuthErrors.Duplicate,
            ErrorCodes.Domain.OAuth.EmailTooLong => OAuthErrors.EmailTooLong,
            ErrorCodes.Domain.OAuth.NotLinked => OAuthErrors.NotLinked,
            ErrorCodes.Domain.OAuth.NowRequired => OAuthErrors.NowRequired,
            ErrorCodes.Domain.OAuth.ProviderInvalid => OAuthErrors.ProviderInvalid,
            ErrorCodes.Domain.OAuth.ProviderRequired => OAuthErrors.ProviderRequired,
            ErrorCodes.Domain.OAuth.ProviderTooLong => OAuthErrors.ProviderTooLong,
            ErrorCodes.Domain.OAuth.ProviderUserIdRequired => OAuthErrors.ProviderUserIdRequired,
            ErrorCodes.Domain.OAuth.ProviderUserIdTooLong => OAuthErrors.ProviderUserIdTooLong,
            ErrorCodes.Domain.OAuth.UserIdRequired => OAuthErrors.UserIdRequired,

            ErrorCodes.Domain.Order.BillingAddressRequired => OrderErrors.BillingAddressRequired,
            ErrorCodes.Domain.Order.CancelNotAllowed => OrderErrors.CancelNotAllowed,
            ErrorCodes.Domain.Order.CancelReasonTooLong => OrderErrors.CancelReasonTooLong,
            ErrorCodes.Domain.Order.CurrencyRequired => OrderErrors.CurrencyRequired,
            ErrorCodes.Domain.Order.DiscountInvalid => OrderErrors.DiscountInvalid,
            ErrorCodes.Domain.Order.ItemCurrencyMismatch => OrderErrors.ItemCurrencyMismatch,
            ErrorCodes.Domain.Order.ItemNotFound => OrderErrors.ItemNotFound,
            ErrorCodes.Domain.Order.ItemRequired => OrderErrors.ItemRequired,
            ErrorCodes.Domain.Order.NotEditable => OrderErrors.NotEditable,
            ErrorCodes.Domain.Order.NotesTooLong => OrderErrors.NotesTooLong,
            ErrorCodes.Domain.Order.NowRequired => OrderErrors.NowRequired,
            ErrorCodes.Domain.Order.NumberRequired => OrderErrors.NumberRequired,
            ErrorCodes.Domain.Order.NumberTooLong => OrderErrors.NumberTooLong,
            ErrorCodes.Domain.Order.PaymentMismatch => OrderErrors.PaymentMismatch,
            ErrorCodes.Domain.Order.PaymentRequired => OrderErrors.PaymentRequired,
            ErrorCodes.Domain.Order.ShippingAddressRequired => OrderErrors.ShippingAddressRequired,
            ErrorCodes.Domain.Order.ShippingFeeInvalid => OrderErrors.ShippingFeeInvalid,
            ErrorCodes.Domain.Order.StatusInvalidTransition => OrderErrors.StatusInvalidTransition,
            ErrorCodes.Domain.Order.TaxInvalid => OrderErrors.TaxInvalid,
            ErrorCodes.Domain.Order.TotalInvalid => OrderErrors.TotalInvalid,
            ErrorCodes.Domain.Order.UserIdRequired => OrderErrors.UserIdRequired,

            ErrorCodes.Domain.OrderItem.CurrencyInvalid => OrderItemErrors.CurrencyInvalid,
            ErrorCodes.Domain.OrderItem.LineTotalInvalid => OrderItemErrors.LineTotalInvalid,
            ErrorCodes.Domain.OrderItem.OrderIdRequired => OrderItemErrors.OrderIdRequired,
            ErrorCodes.Domain.OrderItem.QuantityInvalid => OrderItemErrors.QuantityInvalid,
            ErrorCodes.Domain.OrderItem.SkuRequired => OrderItemErrors.SkuRequired,
            ErrorCodes.Domain.OrderItem.SkuTooLong => OrderItemErrors.SkuTooLong,
            ErrorCodes.Domain.OrderItem.TitleRequired => OrderItemErrors.TitleRequired,
            ErrorCodes.Domain.OrderItem.TitleTooLong => OrderItemErrors.TitleTooLong,
            ErrorCodes.Domain.OrderItem.UnitPriceInvalid => OrderItemErrors.UnitPriceInvalid,
            ErrorCodes.Domain.OrderItem.VariantIdRequired => OrderItemErrors.VariantIdRequired,
            ErrorCodes.Domain.OrderItem.VariantSnapshotRequired => OrderItemErrors.VariantSnapshotRequired,

            ErrorCodes.Domain.Payment.AmountInvalid => PaymentErrors.AmountInvalid,
            ErrorCodes.Domain.Payment.CurrencyRequired => PaymentErrors.CurrencyRequired,
            ErrorCodes.Domain.Payment.NowRequired => PaymentErrors.NowRequired,
            ErrorCodes.Domain.Payment.OrderIdRequired => PaymentErrors.OrderIdRequired,
            ErrorCodes.Domain.Payment.ProviderRequired => PaymentErrors.ProviderRequired,
            ErrorCodes.Domain.Payment.ProviderTooLong => PaymentErrors.ProviderTooLong,
            ErrorCodes.Domain.Payment.ProviderPaymentIdRequired => PaymentErrors.ProviderPaymentIdRequired,
            ErrorCodes.Domain.Payment.ProviderPaymentIdTooLong => PaymentErrors.ProviderPaymentIdTooLong,
            ErrorCodes.Domain.Payment.RefundNotCaptured => PaymentErrors.RefundNotCaptured,
            ErrorCodes.Domain.Payment.StatusFinal => PaymentErrors.StatusFinal,
            ErrorCodes.Domain.Payment.StatusInvalidTransition => PaymentErrors.StatusInvalidTransition,

            ErrorCodes.Domain.Product.ImageRequired => ProductDomainErrors.ImageRequired,
            ErrorCodes.Domain.Product.NowRequired => ProductDomainErrors.NowRequired,
            ErrorCodes.Domain.Product.VariantNotFound => ProductDomainErrors.VariantNotFound,
            ErrorCodes.Domain.Product.VariantPriceOverrideCurrencyMismatch => ProductDomainErrors.VariantPriceOverrideCurrencyMismatch,
            ErrorCodes.Domain.Product.VariantPriceOverrideInvalid => ProductDomainErrors.VariantPriceOverrideInvalid,
            ErrorCodes.Domain.Product.VariantSkuDuplicate => ProductDomainErrors.VariantSkuDuplicate,
            ErrorCodes.Domain.Product.VariantSkuRequired => ProductDomainErrors.VariantSkuRequired,

            ErrorCodes.Domain.Refresh.DeviceInfoTooLong => RefreshErrors.DeviceInfoTooLong,
            ErrorCodes.Domain.Refresh.ExpiresAtInvalid => RefreshErrors.ExpiresAtInvalid,
            ErrorCodes.Domain.Refresh.IpInvalid => RefreshErrors.IpInvalid,
            ErrorCodes.Domain.Refresh.IpTooLong => RefreshErrors.IpTooLong,
            ErrorCodes.Domain.Refresh.NowRequired => RefreshErrors.NowRequired,
            ErrorCodes.Domain.Refresh.ReplacedByRequired => RefreshErrors.ReplacedByRequired,
            ErrorCodes.Domain.Refresh.ReplacedBySame => RefreshErrors.ReplacedBySame,
            ErrorCodes.Domain.Refresh.TokenHashRequired => RefreshErrors.TokenHashRequired,
            ErrorCodes.Domain.Refresh.UserIdRequired => RefreshErrors.UserIdRequired,

            ErrorCodes.Domain.Refund.AmountInvalid => RefundErrors.AmountInvalid,
            ErrorCodes.Domain.Refund.PaymentIdRequired => RefundErrors.PaymentIdRequired,
            ErrorCodes.Domain.Refund.ProviderRefundIdRequired => RefundErrors.ProviderRefundIdRequired,
            ErrorCodes.Domain.Refund.StatusFinal => RefundErrors.StatusFinal,

            ErrorCodes.Domain.UserCredential.PasswordHashInvalid => UserCredentialErrors.PasswordHashInvalid,
            ErrorCodes.Domain.UserCredential.PasswordHashRequired => UserCredentialErrors.PasswordHashRequired,
            ErrorCodes.Domain.UserCredential.UserIdInvalid => UserCredentialErrors.UserIdInvalid,

            ErrorCodes.Domain.Variant.ColorTooLong => VariantDomainErrors.ColorTooLong,
            ErrorCodes.Domain.Variant.ImageRequired => VariantDomainErrors.ImageRequired,
            ErrorCodes.Domain.Variant.InventoryRequired => VariantDomainErrors.InventoryRequired,
            ErrorCodes.Domain.Variant.SizeTooLong => VariantDomainErrors.SizeTooLong,

            ErrorCodes.Domain.VariantImage.SortOrderInvalid => VariantImageErrors.SortOrderInvalid,
            ErrorCodes.Domain.VariantImage.UrlEmpty => VariantImageErrors.UrlEmpty,
            ErrorCodes.Domain.VariantImage.VariantIdEmpty => VariantImageErrors.VariantIdEmpty,

            null or "" or _ => CommonErrors.Validation(),
        };
    }

    public static Error FromCode(string? code, string? fallbackMessage)
    {
        var error = FromCode(code);

        if ((code is null || code.Length == 0 || error.Code != ErrorCodes.Common.Validation) || string.IsNullOrWhiteSpace(fallbackMessage))
        {
            return error;
        }

        return CommonErrors.Validation(fallbackMessage!);
    }
}


